<?php
/** 
 * @method	array	getHostedpage(array $parameters)
 * @method	array	getHostedpages()
 * @method	array	addHostedpagesNewsubscription(array $parameters)
 * @method	array	creatingHostedPageForANewSubscriptionForANewCustomer(array $parameters)
 * @method	array	addHostedpagesUpdatecard(array $parameters)
 * @method	array	addHostedpagesBuyonetimeaddon(array $parameters)
 * @method	array	addHostedpagesUpdatesubscription(array $parameters)
 * @method	array	getTransactions()
 * @method	array	deleteCustomerComment(array $parameters)
 * @method	array	addCustomersMarkasactive()
 * @method	array	addCustomerPaymentreminderDisable(array $parameters)
 * @method	array	addCustomerMarkasactive(array $parameters)
 * @method	array	getCustomers()
 * @method	array	getCustomer(array $parameters)
 * @method	array	getCustomerComments(array $parameters)
 * @method	array	updateCustomer(array $parameters)
 * @method	array	deleteCustomer(array $parameters)
 * @method	array	getCustomerUnusedcredits(array $parameters)
 * @method	array	addCustomersMarkasinactive()
 * @method	array	addCustomer(array $parameters)
 * @method	array	bulkDeleteCustomers()
 * @method	array	addCustomerMarkasinactive(array $parameters)
 * @method	array	addCustomerPaymentreminderEnable(array $parameters)
 * @method	array	deleteCustomerAddress(array $parameters)
 * @method	array	deleteCustomerPaypalaccount(array $parameters)
 * @method	array	deleteProduct(array $parameters)
 * @method	array	updateProduct(array $parameters)
 * @method	array	addProduct(array $parameters)
 * @method	array	getProduct(array $parameters)
 * @method	array	addProductMarkasinactive(array $parameters)
 * @method	array	getProducts()
 * @method	array	markAProductAsInactive(array $parameters)
 * @method	array	deleteSalesperson(array $parameters)
 * @method	array	bulkDeleteSalesperons()
 * @method	array	getSalespersons()
 * @method	array	deleteCreditnoteRefund(array $parameters)
 * @method	array	deleteCreditnote(array $parameters)
 * @method	array	deleteCreditnoteComment(array $parameters)
 * @method	array	getCreditnotesRefund(array $parameters)
 * @method	array	addCreditnoteRefunds(array $parameters)
 * @method	array	deleteCreditnoteInvoice(array $parameters)
 * @method	array	addCreditnoteInvoices(array $parameters)
 * @method	array	addInvoiceEmail(array $parameters)
 * @method	array	addCreditnoteConverttoopen(array $parameters)
 * @method	array	addCreditnoteVoid(array $parameters)
 * @method	array	getCreditnote(array $parameters)
 * @method	array	addCreditnoteCustomfields(array $parameters)
 * @method	array	addCreditnote(array $parameters)
 * @method	array	bulkDeleteCreditnotes()
 * @method	array	getPlans()
 * @method	array	updatePlan(array $parameters)
 * @method	array	addPlan(array $parameters)
 * @method	array	addPlanMarkasinactive(array $parameters)
 * @method	array	addPlanMarkasactive(array $parameters)
 * @method	array	getPlan(array $parameters)
 * @method	array	deletePlan(array $parameters)
 * @method	array	listingAllPlans()
 * @method	array	addSubscriptionNotes(array $parameters)
 * @method	array	addSubscriptionReactivate(array $parameters)
 * @method	array	deleteSubscriptionNote(array $parameters)
 * @method	array	addSubscription(array $parameters)
 * @method	array	addSubscriptionsBulkcancel()
 * @method	array	addSubscriptionLineitem(array $parameters)
 * @method	array	deleteSubscriptionCard(array $parameters)
 * @method	array	updateSubscription(array $parameters)
 * @method	array	addSubscriptionBankaccount(array $parameters)
 * @method	array	getSubscriptions()
 * @method	array	addSubscriptionAutocollect(array $parameters)
 * @method	array	getSubscription(array $parameters)
 * @method	array	addSubscriptionBuyonetimeaddon(array $parameters)
 * @method	array	creatingAnOfflineSubscriptionForAnExistingCustomer(array $parameters)
 * @method	array	addSubscriptionCoupon(array $parameters)
 * @method	array	deleteSubscription(array $parameters)
 * @method	array	getSubscriptionScheduledchanges(array $parameters)
 * @method	array	addSubscriptionCard(array $parameters)
 * @method	array	getSubscriptionRecentactivities(array $parameters)
 * @method	array	getSubscriptionNotes(array $parameters)
 * @method	array	deleteSubscriptionScheduledchanges(array $parameters)
 * @method	array	addSubscriptionCustomfields(array $parameters)
 * @method	array	associateUpdateBankAccountToANewBankAccount(array $parameters)
 * @method	array	addSubscriptionsCompute(array $parameters)
 * @method	array	changeToOfflineMode(array $parameters)
 * @method	array	associateUpdateCardToANewCard(array $parameters)
 * @method	array	addSubscriptionCharge(array $parameters)
 * @method	array	creatingASubscriptionForANewCustomer(array $parameters)
 * @method	array	addSubscriptionCancel(array $parameters)
 * @method	array	addSubscriptionPaypalaccount(array $parameters)
 * @method	array	addSubscriptionPostpone(array $parameters)
 * @method	array	deleteSubscriptionBankaccount(array $parameters)
 * @method	array	addSubscriptionContactpersons(array $parameters)
 * @method	array	addSubscriptionReference(array $parameters)
 * @method	array	listingAllSubscriptionsOfAParticularCustomer()
 * @method	array	addEditDescriptionForAnAddOnInLineItemsList(array $parameters)
 * @method	array	deleteSubscriptionCoupons(array $parameters)
 * @method	array	cancellingASubscriptionAtTheEndOfTerm(array $parameters)
 * @method	array	addSubscriptionSalesperson(array $parameters)
 * @method	array	getCustomerCard(array $parameters)
 * @method	array	deleteCustomerCard(array $parameters)
 * @method	array	addCustomerCards(array $parameters)
 * @method	array	getCustomerCards(array $parameters)
 * @method	array	updateCustomerCard(array $parameters)
 * @method	array	addCouponMarkasactive(array $parameters)
 * @method	array	deleteCoupon(array $parameters)
 * @method	array	updateCoupon(array $parameters)
 * @method	array	addCouponMarkasinactive(array $parameters)
 * @method	array	addCoupon(array $parameters)
 * @method	array	getCoupons()
 * @method	array	getCoupon(array $parameters)
 * @method	array	getOrganizations()
 * @method	array	get()
 * @method	array	getEvent(array $parameters)
 * @method	array	getEvents()
 * @method	array	addPayment(array $parameters)
 * @method	array	getPayment(array $parameters)
 * @method	array	addPaymentRefunds(array $parameters)
 * @method	array	deletePayment(array $parameters)
 * @method	array	updateCustomFieldsForPayment(array $parameters)
 * @method	array	updatePayment(array $parameters)
 * @method	array	getWebhook(array $parameters)
 * @method	array	getWebhooks()
 * @method	array	updateCustomerContactperson(array $parameters)
 * @method	array	addCustomerContactpersons(array $parameters)
 * @method	array	getCustomerContactpersons(array $parameters)
 * @method	array	addCustomerContactpersonPrimary(array $parameters)
 * @method	array	deleteCustomerContactperson(array $parameters)
 * @method	array	getCustomerContactperson(array $parameters)
 * @method	array	deleteCustomerBankaccount(array $parameters)
 * @method	array	updateCustomerBankaccount(array $parameters)
 * @method	array	addCustomerBankaccounts(array $parameters)
 * @method	array	getCustomerBankaccount(array $parameters)
 * @method	array	addAddonMarkasactive(array $parameters)
 * @method	array	addAddon(array $parameters)
 * @method	array	getAddon(array $parameters)
 * @method	array	getAddons()
 * @method	array	listAllAddOnsOfAProduct()
 * @method	array	creatingAnAddonOfTierType(array $parameters)
 * @method	array	creatingAnAddonOfUnitType(array $parameters)
 * @method	array	updateAddon(array $parameters)
 * @method	array	listAllAddOnsAssociatedToAPlan()
 * @method	array	creatingAnAddonOfVolumeType(array $parameters)
 * @method	array	deleteAddon(array $parameters)
 * @method	array	addAddonMarkasinactive(array $parameters)
 * @method	array	addInvoiceCollect(array $parameters)
 * @method	array	updateInvoiceAddress(array $parameters)
 * @method	array	getInvoice(array $parameters)
 * @method	array	downloadAnInvoiceAsAPdfFile(array $parameters)
 * @method	array	addInvoicesSent()
 * @method	array	getInvoices()
 * @method	array	addInvoiceSalesperson(array $parameters)
 * @method	array	addInvoiceComments(array $parameters)
 * @method	array	addInvoicePaymentreminderEnable(array $parameters)
 * @method	array	addInvoiceSent(array $parameters)
 * @method	array	addInvoiceConvertoopen(array $parameters)
 * @method	array	getInvoiceRecentactivities(array $parameters)
 * @method	array	emailAnInvoice(array $parameters)
 * @method	array	deleteInvoiceComment(array $parameters)
 * @method	array	addInvoiceCustomfields(array $parameters)
 * @method	array	addInvoicePaymentreminderDisable(array $parameters)
 * @method	array	getBankaccountPendinginvoices(array $parameters)
 * @method	array	getInvoiceComments(array $parameters)
 * @method	array	addInvoiceWriteoff(array $parameters)
 * @method	array	addInvoiceCancelwriteoff(array $parameters)
 * @method	array	deleteInvoiceCreditsapplied(array $parameters)
 * @method	array	deleteInvoice(array $parameters)
 * @method	array	collectChargeWithBankAccount(array $parameters)
 * @method	array	addInvoicePaymentdate(array $parameters)
 * @method	array	addInvoiceVoid(array $parameters)
 * @method	array	addInvoiceCredits(array $parameters)
 * @method	array	getPricebooks()
 * @method	array	deleteOrganization(array $parameters)
 * @method	array	listingAllOrganizations()
 */
